apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260610-200219-5ylkyx30hb1p-service
spec:
  selector:
    app: enterprise-system-20260610-200219-5ylkyx30hb1p
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
